export const heroes = [
  { id: 1, name: "Superman", city: "Metropolis", power: "Fuerza sobrehumana" },
  { id: 2, name: "Batman", city: "Gotham", power: "Estratega experto" },
  { id: 3, name: "Wonder Woman", city: "Themyscira", power: "Fuerza divina" },
  { id: 4, name: "Flash", city: "Central City", power: "Velocidad sobrehumana" },
  { id: 5, name: "Green Lantern", city: "Coast City", power: "Anillo de poder" },
  { id: 6, name: "Aquaman", city: "Atlantis", power: "Comunicación con criaturas marinas" },
  { id: 7, name: "Cyborg", city: "Detroit", power: "Cuerpo cibernético avanzado" },
  { id: 8, name: "Martian Manhunter", city: "Marte", power: "Cambio de forma y telepatía" },
  { id: 9, name: "Iron Man", city: "Malibú", power: "Armadura tecnológica" },
  { id: 10, name: "Captain America", city: "Brooklyn", power: "Super soldado" },
  { id: 11, name: "Spider-Man", city: "Nueva York", power: "Sentido arácnido y trepar muros" },
  { id: 12, name: "Hulk", city: "Dayton", power: "Fuerza descomunal e invulnerabilidad" },
  { id: 13, name: "Black Widow", city: "Stalingrado", power: "Espionaje y artes marciales" },
  { id: 14, name: "Thor", city: "Asgard", power: "Control del trueno y Mjolnir" },
  { id: 15, name: "Hawkeye", city: "Iowa", power: "Tiro con arco letal" },
  { id: 16, name: "Doctor Strange", city: "Nueva York", power: "Magia mística y portales" },
  { id: 17, name: "Scarlet Witch", city: "Sokovia", power: "Manipulación de la realidad" },
  { id: 18, name: "Vision", city: "Nueva York", power: "Rayo de mente y fase intangible" },
  { id: 19, name: "Black Panther", city: "Wakanda", power: "Agilidad mejorada y vibranium" },
  { id: 20, name: "Ant-Man", city: "San Francisco", power: "Cambio de tamaño y comunicación con insectos" },
  { id: 21, name: "Wasp", city: "San Francisco", power: "Vuelo y rayos bioeléctricos" },
  { id: 22, name: "Star-Lord", city: "Missouri", power: "Habilidad de combate y liderazgo" },
  { id: 23, name: "Gamora", city: "Zen-Whoberi", power: "Asesina entrenada y fuerza mejorada" },
  { id: 24, name: "Drax", city: "Kylos", power: "Resistencia y fuerza brutal" },
  { id: 25, name: "Groot", city: "Planeta X", power: "Regeneración y control de ramas" },
  { id: 26, name: "Rocket Raccoon", city: "Halfworld", power: "Tácticas de guerra y armas pesadas" },
  { id: 27, name: "Shazam", city: "Filadelfia", power: "Magia antigua y fuerza de Hércules" },
  { id: 28, name: "Moon Knight", city: "Chicago", power: "Múltiples personalidades y poderes lunares" },
  { id: 29, name: "Ms. Marvel", city: "Jersey City", power: "Elasticidad y cambio de forma" },
  { id: 30, name: "She-Hulk", city: "Los Ángeles", power: "Fuerza sobrehumana y abogada brillante" }
];
